### ISSUE TITLE
EC2-Scheduler fails if an instance does not have any tags

### ISSUE THREAD

**Issue by benfairless** [LandRegistry-Ops/ec2-scheduler#5]
When an instance is inspected which does not have any tags at all EC2-Scheduler fails.

## Steps to reproduce
- Create a new instance and do not create any tags
- Run EC2-Scheduler

## Error message
```
INFO:EC2 Manager:i-xxxxxxxxxxxxxxxxx - Inspecting instance...
Traceback (most recent call last):
  File "run.py", line 150, in <module>
    i = EC2Instance(instance)
  File "/var/lib/jenkins/jobs/EC2 Scheduler/workspace/ec2.py", line 15, in __init__
    self.validate()
  File "/var/lib/jenkins/jobs/EC2 Scheduler/workspace/ec2.py", line 75, in validate
    for tag in self.tags:
TypeError: 'NoneType' object is not iterable
```

**Comment by benfairless** [comment]
Fixed by @liamark in commit 2613bcc0c1ed55c0344d19b9fdf91ceae16e914a
